services:
  front:
    container_name: terrahub-frontend
    build:
      context: ./
      dockerfile: Dockerfile-front
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./database/:/var/www/database/
    networks:
      - terrahub_network
    ports:
      - ${FRONT_EXPOSED_PORT}:80

networks:
  terrahub_network:
    driver: bridge

volumes:
  mongo_db: {}

