FROM node:22 as node
WORKDIR /app

COPY ./front/package.json .
COPY ./front/package-lock.json .

RUN npm ci

COPY ./front .
RUN npm run build

# Stage 2
FROM nginx:alpine
COPY --from=node /app/dist/terraria-angular /var/www/html/
