services:
  front:
    container_name: terrahub-frontend
    build:
      context: ./
      dockerfile: Dockerfile-front
    volumes:
      - ./nginx/api.conf:/etc/nginx/includes/api.conf
      - ./nginx/${APP_ENV}.conf:/etc/nginx/conf.d/default.conf
      - ./database/:/var/www/database/
    networks:
      - terrahub_network
    ports:
      - ${FRONT_EXPOSED_PORT}:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  terrahub_network:
    driver: bridge

