version: '3.9'

services:
  database:
    container_name: terrahub-mongo
    image: mongo:latest
    restart: always
    command: --port ${MONGO_EXPOSED_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_db:/data/db
      - ./terrahub-database/latest/dump/terrahub:/backup
      - ./terrahub-database/scripts:/restore
      - ./terrahub-database/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - ${MONGO_EXPOSED_PORT}:27017

  server:
    container_name: terrahub-api
    build:
      context: ./
      dockerfile: Dockerfile-api
    restart: always
    environment:
      VERSION: beta
      MODE: dev
      URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@database:${MONGO_EXPOSED_PORT}/terrahub?authSource=terrahub
      PORT: 80
    ports:
      - ${SERVER_EXPOSED_PORT}:80
    depends_on:
      - database

  front:
    container_name: terrahub-frontend
    build:
      context: ./
      dockerfile: Dockerfile-front
    volumes:
      - ./terrahub-nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${FRONT_EXPOSED_PORT}:80
      - 443:443

  dozzle:
    container_name: logs
    image: amir20/dozzle:latest
    env_file:
      - env/dozzle.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

volumes:
  mongo_db: {}
